spec:
  # project: apps-data
  project: default
  destination:
    server: https://kubernetes.default.svc
    namePrefix: ""
  source:
    repoURL: https://github.com/rcompos/demo.git
    targetRevision: main

# GLobal app values file
valueFiles:
  - values.yaml

# Application Definitions
#
# app:
#   appNickname:                      # Go conforming name (camelCase)
#     name: name-of-app-directory     # Directory name where chart residees (required)
#     fullnameOverride: name-of-app   # Override name of app to deploy (optional)
#     values:                         # List of values file (optional)
#       - values.yaml                   # Values file (optional)
#       - values-my-env.yaml            # Values file (optional will be merged)
#     namespace: custom-namespace     # Namespace (optional)
#     repo: https://my-git-server.com/data/my-repo.git   # Git chart repo (optional)
#     path: path/to/my-chart          # Path under chart repo (optional)
#     targetRev: my/branch            # Git branch (optional)
#     ignoreDiffs: true               # Ignore ArgoCD app diffs (true|false)
#     syncOptions:                    # Sync options for sync policy (optional)
#       - CreateNamespace=true          # Example
#
# Example:
#
# apps:
#   myAppName:
#     name: my-app-name
#     fullnameOverride: ""
#     values: []
#     namespace: ""
#     repo: ""
#     path: ""
#     targetRev: ""
#     ignoreDiffs: ""
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
#

# Applications to deploy, including overrides

apps:
  postgresql:
    name: postgresql
  nginx:
    name: nginx
  airflow:
    name: airflow
  jupyterhub:
    name: jupyterhub
  metalLB:
    name: metallb
  