spec:
  # project: proj-infrastructure
  project: default
  destination:
    server: https://kubernetes.default.svc
    namePrefix: ""
  source:
    repoURL: https://github.com/rcompos/demo.git
    targetRevision: main

# GLobal app values file
valueFiles:
  - values.yaml

# Application Definitions
#
# app:
#   appNickname:                      # Go conforming name (camelCase)
#     name: name-of-app-directory     # Directory name where chart residees (required)
#     fullnameOverride: name-of-app   # Override name of app to deploy (optional)
#     values:                         # List of values file (optional)
#       - values.yaml                   # Values file (optional)
#       - values-my-env.yaml            # Values file (optional will be merged)
#     namespace: custom-namespace     # Namespace (optional)
#     repo: https://gitlab.corp.atieva.com/data/my-repo.git   # Git chart repo (optional)
#     path: path/to/my-chart          # Path under chart repo (optional)
#     targetRev: my/branch            # Git branch (optional)

apps:
  nginx:
    name: nginx
    fullnameOverride: ""
    values: []
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""
  airflow:
    name: airflow 
    fullnameOverride: ""
    values: []
    namespace: ""
    repo: ""
    path: ""
    targetRev: ""

